apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocdkubernetes
  namespace: argocd

spec:
  project: "default"
  source:
        targetRevision: HEAD
        repoURL: https://github.com/Shubham-jangidd/notejam_deployment.git
        path: 
  destination:
    server: https://kubernetes.default.svc
    namespace: mynotejamapp
  syncPolicy:
    syncOptions:
    - createNamespace=true

    automated:
      selfHeal: true
      prune: true
